### ISSUE TITLE
codespaces: use latest stable ddev version, not betas?

### ISSUE THREAD

**Issue by mandrasch** [mandrasch/ddev-craftcms-vite#6]
```bash
#15 0.660 ===========================================================================
#15 0.660 Feature       : Install DDEV for Codespaces
#15 0.660 Description   : DDEV feature for Codespaces/devcontainers
#15 0.660 Id            : ghcr.io/ddev/ddev/install-ddev
#15 0.660 Version       : v1.22.0-beta1
#15 0.660 Documentation : 
#15 0.660 Options       :
#15 0.660 
#15 0.660 ===========================================================================
```

https://github.com/orgs/ddev/packages/container/package/ddev%2Finstall-ddev

**Comment by rfay** [comment]
Isn't your script using apt to install? In that case it will always use stable, as we don't even have a way to get betas with apt.

**Comment by mandrasch** [comment]
Hey @rfay, thanks so much for participating on this!

I just use

```
"image": "mcr.microsoft.com/devcontainers/universal:2",
  "features": {
    "ghcr.io/ddev/ddev/install-ddev:latest": {}
  }, 
```

(I haven't figured out what "packages" exactly are in context of codespaces and how the release tagging work. Just saw:

https://github.com/orgs/ddev/packages/container/package/ddev%2Finstall-ddev

![image](https://github.com/mandrasch/ddev-craftcms-vite/assets/777278/ca24ae4b-b6a8-48ee-af17-d41820a0794b)
)

**Comment by rfay** [comment]
That's the version of the latest *package*, nothing changed between that and release, but I guess we should have pushed another one. I definitely plan to push one as soon as your couple of codespaces fixes are done. But you should get latest stable *ddev* regardless.

**Comment by mandrasch** [comment]
😮 This codespaces thing can be confusing!

Thanks very much @rfay for explaining!

Tested `ddev -v` in the codespace instance and it's totally set correct to latest stable version as you said 👍 👍 

```
@mandrasch ➜ /workspaces/ddev-craftcms-vite (main) $ ddev -v
ddev version v1.22.1
```

The output of the creation log with `-beta` confused me. 

```
#15 0.660 ===========================================================================
#15 0.660 Feature       : Install DDEV for Codespaces
#15 0.660 Description   : DDEV feature for Codespaces/devcontainers
#15 0.660 Id            : ghcr.io/ddev/ddev/install-ddev
#15 0.660 Version       : v1.22.0-beta1
``` 

Don't know if a own version number for this feature would be helpful, other codespace features seem to use a own version number for the package https://containers.dev/features. But not a priority at all currently. Thanks again!

**Comment by rfay** [comment]
I want to push a new package with your latest changes (both of them) when they make it in. I was trying to correlate the package with DDEV version (previously it was independent). Now it looks like it wasn't a great idea :)
