### ISSUE TITLE
Disable critical CSS in craft.vite.script() function

### ISSUE THREAD

**Issue by phil-cv** [mandrasch/ddev-craftcms-vite#9]
Because the project doesn't implements critical CSS (and no compelling reason to), the craft.vite.script() function should include `false` as a second parameter to ensure CSS doesn't load asynchronously and cause a flash of unstyled content:

`{{ craft.vite.script("src/js/app.js", false) }}`

See https://nystudio107.com/docs/vite/#using-vite for details.

**Comment by mandrasch** [comment]
Hi! Oh wow, thanks very much for reporting! 💡
